### ISSUE TITLE
Folder/File Icons missing

### ISSUE THREAD

**Issue by jkronen** [focmb/seafile_custom_css_green#1]
Hey, thank you for this great theme. But the Icons of the crypted Libraries, read only Libraries, Folders and several filetypes (music, textfile, ...) are still in their original color.

Additional the favicon is still orange. Maybe you can provide it in the same color style as the rest.

**Comment by focmb** [comment]
I am working on this. I search a way to change the icons so that the changes alive a server update. But I will provide green icons a description, how to change the icons for the current way. But then you must copy the icons after every seafile server update

**Comment by focmb** [comment]
no simple solution. See the README for a non persistent solution
