### ISSUE TITLE
Please Update the CSS Files

### ISSUE THREAD

**Issue by TMHBOFH** [focmb/seafile_custom_css_green#4]
Hi,
**thanks for the great work.**

Since version 6.1.3 there are new objects and it would be great if you could adapt the css files.

Thanks again

![seafile-css](https://user-images.githubusercontent.com/12548049/28053842-e3559df4-6612-11e7-8aec-193089f2c2f6.png)

**Comment by focmb** [comment]
I will try it but I have to wait for the 6.1.3 version for raspberry pi because I am running seafile on my raspberry and I can only test the css-file on the pi.

**Comment by TMHBOFH** [comment]
**Thanks**

i hope the next CE release is coming soon

**Comment by TMHBOFH** [comment]
Hi,
the new version 6.1.2 is online.
**Thanks**

**Comment by focmb** [comment]
Installed the update. will check the gui for orange parts

**Comment by TMHBOFH** [comment]
Hi,

please see https://forum.seafile.com/t/seafile-server-6-1-2-sidebar-issue/3802/7

**Comment by focmb** [comment]
I have installed the new version 6.2.1 and working on the css file

**Comment by focmb** [comment]
Fixed the sidebar issue with the solution from your link. Thanks.

Working now on some orange parts

**Comment by TMHBOFH** [comment]
**THANKS**
