### ISSUE TITLE
Issues in settings panel by using custom.css

### ISSUE THREAD

**Issue by focmb** [focmb/seafile_custom_css_green#8]
By using the original css-file all is working fine. But the settings panel (personal settings and admin settings) is broken while using the custom.css (see screenshot)
![bildschirmfoto von 2018-07-13 13-19-41](https://user-images.githubusercontent.com/261217/42689236-bf1e940a-869f-11e8-9286-77796cae681c.png)

**Comment by focmb** [comment]
fixed this issue for the desktop version. for mobile browsers the fix isn't working. the gui in mobile browsers is stillbroken

**Comment by kocane** [comment]
Something has also been changed in the header where the upload button and so on are located.

Should look like this:
![image](https://user-images.githubusercontent.com/7694813/42817499-921b10be-89ce-11e8-8205-e3cf9659719c.png)

But looks like this:
![image](https://user-images.githubusercontent.com/7694813/42817456-75285c78-89ce-11e8-82f3-3995f2101d9c.png)

Obviously quite minor but that's one of the things I spotted.

Thanks for the fix, I really dislike the orange colour Seafile has.

**Comment by focmb** [comment]
Added a new branch (v6_3_2) for the new seafile version. The settings panel is working now in desktop and mobile version. Currently I working on this branch for some small issues and try to change some elements in orange to green

**Comment by focmb** [comment]
issuer in settings panel and other elements are fixed for seafile server 6.3.2. For seafile server 6.2.5 use the custom.css from branch v6_2_5.

I think there are some small elements in orange that I forgot. If u find some of these please open a new ticket.
